---
# tasks file for minio

- name: Create minio system group
  group:
    name: "{{ minio_group }}"
    state: present
    system: yes

- name: Create minio user
  user:
    name: "{{ minio_user }}"
    system: yes
    shell: /sbin/nologin
    group: "{{ minio_group }}"

- name: Download MinIO Server
  ansible.builtin.get_url:
    url: https://dl.min.io/server/minio/release/linux-amd64/minio
    dest: /usr/local/bin
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: 0755

- name: Install supplementary packages
  dnf:
    name: "{{ item }}"
    state: latest
  loop: "{{ packages.redhat }}"

# - name: download MinIO Client
#   get_url:
#     url: https://dl.min.io/client/mc/release/linux-amd64/mc
#     dest: /usr/local/bin
#     owner: "{{ minio_user }}"
#     group: "{{ minio_group }}"
#     mode: 0755

# - name: Turn On packet forwarding in order HAProxy to start
#   sysctl:
#     name: net.ipv4.ip_forward
#     value: "1"
#     sysctl_set: yes

# - name: Turn On Non-Local binding in order HAProxy to start
#   sysctl:
#     name: net.ipv4.ip_nonlocal_bind
#     value: "1"
#     sysctl_set: yes

- name: Create minio storage and config directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0755'
  loop:
    - /etc/minio
    - ${HOME}/.minio/certs

- name: Copy minio envirionment variables
  template:
    src: minio.env.j2
    dest: /etc/default/minio
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0644'
  notify: Restart minio

- name: Copy minio systemd service
  get_url:
    url: https://raw.githubusercontent.com/minio/minio-service/master/linux-systemd/minio.service
    dest: /etc/systemd/system/
    mode: '0644'

- name: Change the username in the Systemd unit file
  replace:
    path: /etc/systemd/system/minio.service
    regexp: 'User=minio-user'
    replace: 'User={{ minio_user }}'

- name: Change the minio_group name in the Systemd unit file
  replace:
    path: /etc/systemd/system/minio.service
    regexp: 'Group=minio-user'
    replace: 'Group={{ minio_group }}'

- name: Just force systemd to re-execute itself (2.8 and above)
  systemd:
    daemon_reexec: yes

# - name: Allowing firewall rules for ports
#   firewalld:
#     port: "{{ item }}"
#     permanent: yes
#     state: enabled
#   notify: Restart firewalld
#   loop:
#     - "{{ minio_server_port }}/tcp"

# - name: Copy TLS certificates
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     owner: "{{ minio_user }}"
#     group: "{{ minio_group }}"
#     remote_src: yes
#   loop:
#     - { src: "/etc/letsencrypt/live/{{ fqdn }}/privkey.pem", dest: "/home/{{ become_user }}/.minio/certs/privkey.key" }
#     - { src: "/etc/letsencrypt/live/{{ fqdn }}/fullchain.pem", dest: "/home/{{ become_user }}/.minio/certs/public.crt" }

# - name: Set cap_net_bind_service=+ep on ./minio
#   capabilities:
#     path: /home/{{ become_user }}/.minio
#     capability: cap_net_bind_service=+ep
#     state: present

- name: Start minio service
  service:
    name: minio
    state: started
    enabled: yes
