---
# handlers file for minio

- name: Restart firewalld
  systemd:
    name: firewalld
    state: restarted
    daemon_reload: yes

- name: Restart minio
  systemd:
    name: minio
    state: restarted
    # daemon_reload: yes
